name: publish
on:
  push:
    branches:
      - main
jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
        working-directory: ./website
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        env:
          REACT_APP_API_HOST: ${{ secrets.API_HOST }}
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          working-dir: ./website
